### ISSUE TITLE
Exception: Unable to find JAVA_HOME

### ISSUE THREAD

**Issue by MaoMaoStudents** [sunnweiwei/RankGPT#29]
Dear Author,

Thank you for your open-source contribution. I would like to ask you a question regarding the environment setup.

When running the following line of code:

from pyserini.search import LuceneSearcher, get_topics, get_qrels
I encounter the following error:

Traceback (most recent call last):
  File "D:\PycharmProjects\RankGPT\demo.py", line 3, in <module>
    from pyserini.search import get_qrels
  File "D:\ProgramData\Anaconda3\envs\rankgpt-3.12\Lib\site-packages\pyserini\search\__init__.py", line 17, in <module>
    from ._base import get_topics, get_topics_with_reader, get_qrels_file, get_qrels
  File "D:\ProgramData\Anaconda3\envs\rankgpt-3.12\Lib\site-packages\pyserini\search\_base.py", line 25, in <module>
    from pyserini.pyclass import autoclass
  File "D:\ProgramData\Anaconda3\envs\rankgpt-3.12\Lib\site-packages\pyserini\pyclass.py", line 31, in <module>
    from jnius import autoclass, cast
  File "D:\ProgramData\Anaconda3\envs\rankgpt-3.12\Lib\site-packages\jnius\__init__.py", line 18, in <module>
    java = get_java_setup(sys.platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\rankgpt-3.12\Lib\site-packages\jnius\env.py", line 60, in get_java_setup
    JAVA_HOME = get_jdk_home(platform)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\rankgpt-3.12\Lib\site-packages\jnius\env.py", line 335, in get_jdk_home
    raise Exception('Unable to find JAVA_HOME')
Exception: Unable to find JAVA_HOME
Apart from the environment specified in requirements.txt, is there any additional setup required? Looking forward to your reply!

**Comment by sunnweiwei** [comment]
Hi! Installing Pyserini on Windows can be tricky. You can refer to the official repo for more details: [Pyserini](https://github.com/castorini/pyserini), [Anserini (dependency)](https://github.com/castorini/anserini). In Anserini, the *Windows tips* mention: “If you are using Windows, please use WSL2 to build Anserini.”

Alternatively, you can avoid using Pyserini if you only need to: (i) Download data, consider using [ir-datasets](https://ir-datasets.com/). (ii) Run BM25 retrieval, consider [bm25s](https://github.com/xhluca/bm25s), which doesn’t require Java.

Hope this helps!

**Comment by MaoMaoStudents** [comment]
thanks for your reply！it helps me a lot！look forward for your future work～

---- Replied Message ----
| From | Weiwei ***@***.***> |
| Date | 12/30/2024 10:13 |
| To | sunnweiwei/RankGPT ***@***.***> |
| Cc | MaoMaoStudents ***@***.***>,
Author ***@***.***> |
| Subject | Re: [sunnweiwei/RankGPT] Exception: Unable to find JAVA_HOME (Issue #29) |

Hi! Installing Pyserini on Windows can be tricky. You can refer to the official repo for more details: Pyserini, Anserini (dependency). In Anserini, the Windows tips mention: “If you are using Windows, please use WSL2 to build Anserini.”

Alternatively, you can avoid using Pyserini if you only need to: (i) Download data, consider using ir-datasets. (ii) Run BM25 retrieval, consider bm25s, which doesn’t require Java.

Hope this helps!
